### ISSUE TITLE
I've expanded your script into a complete project

### ISSUE THREAD

**Issue by nordurljosahvida** [algernon/mastodon-backup#1]
Hi there! A non-issue here but rather a feedback.
Thanks for your great code. I've made this into a full blown project called [incognitum](https://github.com/openspace42/incognitum/) with the following features:

```

    One touch, three minute install
    Set-it-and-forget-it backups will automatically run a backup of all your sites every night and email you in case of failure
    Works with both Docker / Non-Docker installation types [not yet implemented / work in progress]
    Stores backups both locally and remotely [on S3]
    Encrypts all remote backups with a 42 character passphrase
    Requires no configuration inside Mastodon and/or Docker, everything happens on the filesystem level completely unbeknownst to the application / containers themselves.
    Performs a test restore before every S3 backup to ensure remote backup integrity and passphrase match
    Allows you to restore your backup with one single command and a maximum of three minutes of your time even from a blank machine you've never set up before [not yet implemented / work in progress]
    Perfectly restores every aspect of the Mastodon instance you're hosting, from your database, to all of your files
    Outputs clean and colorful logs and stores them automatically inside its own log directory

```

For now restores and Non-Docker backups are not yet implemented, but Docker backup works great! In fact, this code is what's keeping our mastodon instance https://md.os.vu backed up every day on S3! If you happen to be running Debian/Ubuntu and have an active Mastodon installation, please try it out and let me know how it's working for you!

Would you be interested on writing the Non-Docker and / or restore parts collaboratively?

Thanks!

**Comment by algernon** [comment]
Glad to hear this has been useful to you, and thank you for letting me know! <3

As for writing the non-docker or restore parts: non-docker is something I'm not interested in, I only run one Mastodon instance, and do that through Docker, not planning to change that, so I have no way to test non-docker stuff (nor do I have the time, anyway...)

Regarding restore... well... since I wrote this script, I switched to other backup methods, so I have no immediate need for restoration support either (I do full-disk snapshots once a week).
